### ISSUE TITLE
MQTT with Hichi Wifi Lesekopf

### ISSUE THREAD

**Issue by espamis** [andyboeh/esphome-amis#2]
Hi and thank you for creating this repository! 

two questions:
1. Does your meter transmit once per second without any action from your part?
In my case I do not see any blinking when I check with my smartphone camera and
I think I should see something.
I do see the message `bytes available, reading` in the log and over MQTT. It
appears once per minute. Sadly nothing more and no consumption data.

2. When trying to run this independent of HomeAssistant, is it OK to skip  
```
 - platform: total_daily_energy
    name: "AMIS Daily Energy"
    power_id: instantaneous_power_a
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:clock-alert
```

and

```
time:
  - platform: homeassistant
    id: homeassistant_time
```
?

My code does not compile with it.

**Comment by espamis** [comment]
Additional details:
I am trying to use your code to transmit my consumption via MQTT using an ESP01s
connected to the IR module bought from Ebay.
> WIFI lesekopf lese-schreib-Kopf EHZ Volkszähler Hichi Smartmeter

This is not the perfect solution yet since ESPHome does not allow for TLS over
MQTT with LetsEncrypt certificates.
But since Tasmota does not seem to offer any support for decrypting the AES
data from the meter, I am very grateful for your code.

**Comment by espamis** [comment]
Further information, in case anybody wants to replicate this:

Compiling does not work with the most current esphome version, so get when
installing it, make sure you use an older version:
`pip install esphome==1.19.0`

Since I come from Tasmota and do not run any HomeAssistant code, I prefer
enabling the web interface to be able to manage the firmware.

Below you can find my full configuration:

```
esphome:
  name: powermeter
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Example configuration entry
mqtt:
  broker: 192.168.1.1
  port: 1883
  username: mqtt_user
  password: mqtt_password

ota:
  password: ""

wifi:
  ssid: "mywifiname"
  password: "mywifipassword"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Powermeter Fallback Hotspot"
    password: "powermeterfallbackhotspotpassword"

captive_portal:

external_components:
  - source: github://andyboeh/esphome-amis
    components: amis

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  parity: EVEN

sensor:
  - platform: amis
    power_grid_key: 1234567890ABCDEF1234567890ABCDEF
    energy_a_positive:
      name: Energy A+
    energy_a_negative:
      name: Energy A-
    reactive_energy_a_positive:
      name: Reactive Energy A+
    reactive_energy_a_negative:
      name: Reactive Energy A-
    instantaneous_power_a_positive:
      name: "Instantaneous Power A+"
      id: instantaneous_power_a
    instantaneous_power_a_negative:
      name: Instantaneous Power A-
    reactive_instantaneous_power_a_positive:
      name: Reactive Instantaneous Power A+
    reactive_instantaneous_power_a_negative:
      name: Reactive Instantaneous Power A-

web_server:
  port: 80

```

**Comment by andyboeh** [comment]
Regarding your first question: No, if you don't do anything, it does not transmit every second. The behavior is as follows:

The meter sends its data once per minute. If the software acknowledges such a frame within a given time frame, it starts transmitting once per second as long as the frames are acknowledged. You should also see the message `ack'ed frame` if this happens.

You answered the second question yourself :)

If you don't use Home Assistant, you might be better off using the software my implementation is based on: http://www.mitterbaur.at/amis-leser.html It runs on an ESP8266, does not use ESPHome and provides an MQTT connection.

**Comment by andyboeh** [comment]
Thanks for pointing out the incompatibility with the latest version of ESPHome. Since I do not update my AMIS ESP on a regular basis, it takes some time for me to notice required changes. I just pushed an update to address this issue.

**Comment by espamis** [comment]
Thank you for the quick update and all your help! It works for me now. We also get a nicer web UI with dark mode.

For anyone else trying the same thing as I was:

When the logger is enabled, esphome (at least on my ESP01s/ESP8266) only manages to parse the first 10 or so messages (seconds) after each full minute. So while useful for debugging, in this mode you have to be patient and let it run (in some cases this was a few hours) to get it to "sync" with the meter to finally receive some data. During this time I saw `bytes available, reading` every minute but nothing more.

A second problem was with the MQTT timeout, which by default reboots the ESP after 15 minutes, if there is no connection to the broker. This also interrupts the syncing process, and was the case for me.

So for first setup and with debug logging, I recommend the following code:
```
esphome:
  name: powermeter
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

mqtt:
  broker: 192.168.1.1
  port: 1883
  username: mqtt_user
  password: mqtt_password
  reboot_timeout: 0s

ota:
  password: ""

wifi:
  ssid: "mywifiname"
  password: "mywifipassword"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Powermeter Fallback Hotspot"
    password: "powermeterfallbackhotspotpassword"

captive_portal:

external_components:
  - source: github://andyboeh/esphome-amis
    components: amis

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  parity: EVEN

sensor:
  - platform: amis
    power_grid_key: 1234567890ABCDEF1234567890ABCDEF
    energy_a_positive:
      name: Energy A+
    energy_a_negative:
      name: Energy A-
    reactive_energy_a_positive:
      name: Reactive Energy A+
    reactive_energy_a_negative:
      name: Reactive Energy A-
    instantaneous_power_a_positive:
      name: "Instantaneous Power A+"
      id: instantaneous_power_a
    instantaneous_power_a_negative:
      name: Instantaneous Power A-
    reactive_instantaneous_power_a_positive:
      name: Reactive Instantaneous Power A+
    reactive_instantaneous_power_a_negative:
      name: Reactive Instantaneous Power A-

web_server:
  port: 80
```

Once everything works as expected and one would like to receive values every second, the logger has to be disabled:
```
esphome:
  name: powermeter
  platform: ESP8266
  board: esp01_1m

# Enable logging
#logger:

mqtt:
  broker: 192.168.1.1
  port: 1883
  username: mqtt_user
  password: mqtt_password
  reboot_timeout: 0s

ota:
  password: ""

wifi:
  ssid: "mywifiname"
  password: "mywifipassword"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Powermeter Fallback Hotspot"
    password: "powermeterfallbackhotspotpassword"

captive_portal:

external_components:
  - source: github://andyboeh/esphome-amis
    components: amis

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  parity: EVEN

sensor:
  - platform: amis
    power_grid_key: 1234567890ABCDEF1234567890ABCDEF
    energy_a_positive:
      name: Energy A+
    energy_a_negative:
      name: Energy A-
    reactive_energy_a_positive:
      name: Reactive Energy A+
    reactive_energy_a_negative:
      name: Reactive Energy A-
    instantaneous_power_a_positive:
      name: "Instantaneous Power A+"
      id: instantaneous_power_a
    instantaneous_power_a_negative:
      name: Instantaneous Power A-
    reactive_instantaneous_power_a_positive:
      name: Reactive Instantaneous Power A+
    reactive_instantaneous_power_a_negative:
      name: Reactive Instantaneous Power A-

web_server:
  port: 80
```

> If you don't use Home Assistant, you might be better off using the software my implementation is based on: http://www.mitterbaur.at/amis-leser.html It runs on an ESP8266, does not use ESPHome and provides an MQTT connection.

This sadly did not fulfil my requirements, as it does not offer OTA updates (at least as far as I could tell), which was crucial for my application.
