### ISSUE TITLE
proposed update to example_amis.yaml

### ISSUE THREAD

**Issue by grisu122** [andyboeh/esphome-amis#3]
Hi thank you for this repository.

it took me a while to find it but now it is working for me. To my understanding there have been changes to the home assistants energy dashboard which probably require following updates to the example_amis.yaml.
By default the 'state_class:' is 'measurement' and should be now 'total_increasing' to be recognized by home assitants energy dashboard.

```
  - platform: amis
    power_grid_key: 1234567890ABCDEF1234567890ABCDEF
    energy_a_positive:
      name: "Energy A+"
      state_class: total_increasing
    energy_a_negative:
      name: "Energy A-"
      state_class: total_increasing
```

Another update probably necessary is to the configuration.yaml regarding 'last_reset:'. If missing it creates a warning on the energy dashboard. I was not able to add 'last_reset:' in the example_amis.yaml and therefore configuration.yaml requires an update:
```
homeassistant:
  customize_glob:
    sensor.*energy_a*:
      last_reset: '1970-01-01T00:00:00+00:00'
```
